export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAILED = 'ORDER_CREATE_FAILED'

export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_GET_FAILED = 'ORDER_GET_FAILED'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED'

export const ORDER_MARK_REQUEST = 'ORDER_MARK_REQUEST'
export const ORDER_MARK_SUCCESS = 'ORDER_MARK_SUCCESS'
export const ORDER_MARK_FAILED = 'ORDER_MARK_FAILED'
export const ORDER_MARK_RESET = 'ORDER_MARKE_RESET'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILED = 'ORDER_PAY_FAILED'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_LIST_MYORDER_REQUEST = 'ORDER_LIST_MYORDER_REQUEST'
export const ORDER_LIST_MYORDER_SUCCESS = 'ORDER_LIST_MYORDER_SUCCESS'
export const ORDER_LIST_MYORDER_FAILED = 'ORDER_LIST_MYORDER_FAILED'
export const ORDER_LIST_MYORDER_RESET = 'ORDER_LIST_MYORDER_RESET'